### ISSUE TITLE
opt_eegStruct

### ISSUE THREAD

**Issue by MinHoLee-ku** [PatternRecognition/OpenBMI#33]
1. make the scripts as regular format
2. delete the warning message "Warning: Fieldnames are not unique between structures. " at line 18
3. error message when the input variable 'field' is empty -> check all other cases

**Comment by seonminkim-git** [comment]
I just made a line "warning('catstruct:DuplicatesFound','Fieldnames are not unique between structures.') ;" in opt_catStruct function as a comment.
It doesn't check the duplicated fields from two data structure has same value or not, just checking duplication.
