### ISSUE TITLE
opt_eegStruct 

### ISSUE THREAD

**Issue by MinHoLee-ku** [PatternRecognition/OpenBMI#38]
Block a variety of error messages by giving warning when:
1. variable 'field' is empty.
2. the variable 'field' has unacceptable value
example:
field=[] or
field={'x','t','fs','y_dec','y_logic','y_class','class', 'chan', 'aaa', 'aefaef'};

consider other type of errors

**Comment by seonminkim-git** [comment]
done, only for those 2 cases
