### ISSUE TITLE
regular form of functions

### ISSUE THREAD

**Issue by MinHoLee-ku** [PatternRecognition/OpenBMI#40]
It needs to change all scripts to regular format as below:
delete one of function prep_removeClass or prep_removeClass2

prep_addChannels
prep_addFeatures
prep_addTrials
prep_average
prep_baseline
prep_cutDim
prep_defineClass
prep_deleteChannel
prep_erpMeans
prep_removeClass
prep_removeClass2
prep_resample
prep_segmentation
prep_selectChannels
prep_selectClass
prep_selectClasses
prep_selectTime
prep_selectTrials

**Comment by seonminkim-git** [comment]
Function of 'prep_selectClass' and 'prep_selectClasses' is overlapped.
I'll delete one of them, and modify other functions that use prep_selectClass(es).

**Comment by seonminkim-git** [comment]
1. I don't know a function named 'prep_rejectArtifactMAxMin' in preprocessing directory well, so I left it.
2. I moved 'prep_localAverageReference' and 'prep_spectrum' to etc folder.
