### ISSUE TITLE
regular form of functions

### ISSUE THREAD

**Issue by MinHoLee-ku** [PatternRecognition/OpenBMI#41]
It needs to change all scripts to regular format as below:

prep_commonAverageReference
prep_envelope
prep_filter
prep_laplacian
prep_localAverageReference
prep_movingAverage
prep_normalize
prep_rejectArtifactMAxMin
prep_spectrum

**Comment by JeongJiHoon** [comment]
Okay, I have changed all scripts to the regular format.

**Comment by JeongJiHoon** [comment]
I have done. Please check this files and kindly let me know if you have additional requirements
Have a nice day :)
