### ISSUE TITLE
Revising the prep_spectrum function

### ISSUE THREAD

**Issue by JeongJiHoon** [PatternRecognition/OpenBMI#45]
Hi, YoungJin

If you do not require this function, you will remove this function. I think.
Please check the \etc\prep_spectrum function.

**Comment by YoungjinKee** [comment]
Hi, JiHoon

I was forgot to remove this function. I will check the function and update soon.

**Comment by YoungjinKee** [comment]
Removing prep_spectrum now.

**Comment by JeongJiHoon** [comment]
Ok. excellent
