### ISSUE TITLE
Data description

### ISSUE THREAD

**Issue by kolcs** [PatternRecognition/OpenBMI#53]
Dear Developers!

I downloaded the data from http://gigadb.org/dataset/view/id/100542 but I miss some information about the .mat structure. Im investigating one of the *_EEG_MI.mat files:

- are the train and test sets recorded on the same day without removing the EEG system?
- what is the unit of x? (Which I supose is the raw eeg signal) Is it in Volt, miliVolt, microVolt or in an other region eg: 1e-7
- what is the EMG data? Are those EOG channels? If yes what are the positions?
- what are the following fileds: i_val, pre_test, post_test, rest_interval

Thanks in advance!
Csaba Köllőd

**Comment by prmldkhan** [comment]
Thank you for your interest in our dataset.
- are the train and test sets recorded on the same day without removing the EEG system?
 Yes

- what is the unit of x? (Which I supose is the raw eeg signal) Is it in Volt, miliVolt, microVolt or in an other region eg: 1e-7
The unit is microVolt, and Resolution in "unit" is 0.1

- what is the EMG data? Are those EOG channels? If yes what are the positions?
We recorded EMG from each flexor digitorum profundus muscle with the olecranon used as reference.

- what are the following fileds: i_val, pre_test, post_test, rest_interval 
i_val is the Interval of segmented data expressed in ms resolution.
The remaining fields are those related to the pre and post "Rest" data.

For more information, please refer to our GigaScience paper https://academic.oup.com/gigascience/article/8/5/giz002/5304369#134689909.
