### ISSUE TITLE
PreProcessing: Basic Data Structure Processing - selecting, appending, etc. 

### ISSUE THREAD

**Issue by MinHoLee-ku** [PatternRecognition/OpenBMI#8]
The basig EEG signal processing:
1. selecting channel/classes/trials/time interval
2. appending channel/classes/trials, and appeding each of continous EEG data

**Comment by MinHoLee-ku** [comment]
The functions need to consider when input data are more than 2. 
For example,  
prep_addTrials(dat1, dat2) also prep_addTrials({dat1, dat2, dat3, ...})

**Comment by seonminkim-git** [comment]
Thanks for your comment @MinHoLee-ku .
I was about to add that part you said. It will be updated soon.

**Comment by seonminkim-git** [comment]
All these parts are done, though they need to be verified and optimized.
I'm now working on the functions - normalize, baseline and grandAverage.
It takes time to understand the function and deciding which options should be added.
